### PR TITLE
Travis CI: Upgrade libffi6 --> libffi7 for Ubuntu focal

### PR DESCRIPTION
**Pull request by cclauss**
https://packages.ubuntu.com/source/focal/libffi

https://travis-ci.org/github/pepijndevos/futhark-pycffi/pull_requests

### CODE REVIEW

**Comment by pepijndevos** [comment]
Thanks!

**Comment by pepijndevos** [comment]
(I've added you as a collaborator to the repo btw)

**Comment by cclauss** [comment]
This was merged but the Travis CI tests are failing... https://travis-ci.org/github/pepijndevos/futhark-pycffi/pull_requests

Perhaps we need to roll back to an older Ubuntu distro like Xenial instead of Focal.

**Comment by pepijndevos** [comment]
Yea. Hm. `/usr/bin/ld: cannot find -lOpenCL`
Well, you have commit access now, so you can experiment a bit without making a PR for every attempt.

**Pull request merged**
